default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development
  username: root
  password: Pl343434!
  host: localhost

test:
  <<: *default
  database: your_app_test
  username: root
  password: Pl343434!
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
