default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: projekt
  password: password1

development:
  <<: *default
  adapter: postgresql
  database: projekt_development
  username: projekt
  password: password1

test:
  <<: *default
  adapter: postgresql
  database: projekt_test
  username: projekt
  password: password1
  host: localhost


production:
  <<: *default
  adapter: postgresql
  database: projekt_prod
  username: projekt
  password: password1
  url: <%= ENV['DATABASE_URL'] %>
